"""
URL Registry — Versioned allowlist of all source URLs.

Each entry carries metadata used downstream by the scraping service,
chunker, and embedding pipeline. Only URLs listed here are fetched;
the system never crawls beyond this registry.
"""

URL_REGISTRY = [
    {
        "url": "https://groww.in/mutual-funds/parag-parikh-long-term-value-fund-direct-growth",
        "source_type": "groww_scheme_page",
        "scheme_name": "Parag Parikh Flexi Cap Fund",
        "scheme_id": "ppfas_flexi_cap",
        "amc": "PPFAS Mutual Fund",
        "category": "equity",
        "sub_category": "flexi_cap",
    },
    {
        "url": "https://groww.in/mutual-funds/parag-parikh-large-cap-fund-direct-growth",
        "source_type": "groww_scheme_page",
        "scheme_name": "Parag Parikh Large Cap Fund",
        "scheme_id": "ppfas_large_cap",
        "amc": "PPFAS Mutual Fund",
        "category": "equity",
        "sub_category": "large_cap",
    },
    {
        "url": "https://groww.in/mutual-funds/parag-parikh-elss-tax-saver-fund-direct-growth",
        "source_type": "groww_scheme_page",
        "scheme_name": "Parag Parikh ELSS Tax Saver Fund",
        "scheme_id": "ppfas_elss",
        "amc": "PPFAS Mutual Fund",
        "category": "equity",
        "sub_category": "elss",
    },
    {
        "url": "https://groww.in/mutual-funds/parag-parikh-conservative-hybrid-fund-direct-growth",
        "source_type": "groww_scheme_page",
        "scheme_name": "Parag Parikh Conservative Hybrid Fund",
        "scheme_id": "ppfas_conservative_hybrid",
        "amc": "PPFAS Mutual Fund",
        "category": "hybrid",
        "sub_category": "conservative_hybrid",
    },
    {
        "url": "https://groww.in/mutual-funds/parag-parikh-arbitrage-fund-direct-growth",
        "source_type": "groww_scheme_page",
        "scheme_name": "Parag Parikh Arbitrage Fund",
        "scheme_id": "ppfas_arbitrage",
        "amc": "PPFAS Mutual Fund",
        "category": "hybrid",
        "sub_category": "arbitrage",
    },
    {
        "url": "https://groww.in/mutual-funds/parag-parikh-liquid-fund-direct-growth",
        "source_type": "groww_scheme_page",
        "scheme_name": "Parag Parikh Liquid Fund",
        "scheme_id": "ppfas_liquid",
        "amc": "PPFAS Mutual Fund",
        "category": "debt",
        "sub_category": "liquid",
    },
    {
        "url": "https://groww.in/mutual-funds/parag-parikh-dynamic-asset-allocation-fund-direct-growth",
        "source_type": "groww_scheme_page",
        "scheme_name": "Parag Parikh Dynamic Asset Allocation Fund",
        "scheme_id": "ppfas_dynamic_aa",
        "amc": "PPFAS Mutual Fund",
        "category": "hybrid",
        "sub_category": "dynamic_asset_allocation",
    },
    # ── JioBlackRock Mutual Fund ──────────────────────────────────────────
    {
        "url": "https://groww.in/mutual-funds/jioblackrock-flexi-cap-fund-direct-growth",
        "source_type": "groww_scheme_page",
        "scheme_name": "JioBlackRock Flexi Cap Fund",
        "scheme_id": "jbr_flexi_cap",
        "amc": "JioBlackRock Mutual Fund",
        "category": "equity",
        "sub_category": "flexi_cap",
    },
    {
        "url": "https://groww.in/mutual-funds/jioblackrock-nifty-smallcap-250-index-fund-direct-growth",
        "source_type": "groww_scheme_page",
        "scheme_name": "JioBlackRock Nifty SmallCap 250 Index Fund",
        "scheme_id": "jbr_nifty_smallcap_250",
        "amc": "JioBlackRock Mutual Fund",
        "category": "equity",
        "sub_category": "index",
    },
    {
        "url": "https://groww.in/mutual-funds/jioblackrock-liquid-fund-direct-growth",
        "source_type": "groww_scheme_page",
        "scheme_name": "JioBlackRock Liquid Fund",
        "scheme_id": "jbr_liquid",
        "amc": "JioBlackRock Mutual Fund",
        "category": "debt",
        "sub_category": "liquid",
    },
    {
        "url": "https://groww.in/mutual-funds/jioblackrock-nifty-50-index-fund-direct-growth",
        "source_type": "groww_scheme_page",
        "scheme_name": "JioBlackRock Nifty 50 Index Fund",
        "scheme_id": "jbr_nifty_50",
        "amc": "JioBlackRock Mutual Fund",
        "category": "equity",
        "sub_category": "index",
    },
    {
        "url": "https://groww.in/mutual-funds/jioblackrock-nifty-midcap-150-index-fund-direct-growth",
        "source_type": "groww_scheme_page",
        "scheme_name": "JioBlackRock Nifty Midcap 150 Index Fund",
        "scheme_id": "jbr_nifty_midcap_150",
        "amc": "JioBlackRock Mutual Fund",
        "category": "equity",
        "sub_category": "index",
    },
    {
        "url": "https://groww.in/mutual-funds/jioblackrock-sector-rotation-fund-direct-growth",
        "source_type": "groww_scheme_page",
        "scheme_name": "JioBlackRock Sector Rotation Fund",
        "scheme_id": "jbr_sector_rotation",
        "amc": "JioBlackRock Mutual Fund",
        "category": "equity",
        "sub_category": "sectoral",
    },
    {
        "url": "https://groww.in/mutual-funds/jioblackrock-nifty-next-50-index-fund-direct-growth",
        "source_type": "groww_scheme_page",
        "scheme_name": "JioBlackRock Nifty Next 50 Index Fund",
        "scheme_id": "jbr_nifty_next_50",
        "amc": "JioBlackRock Mutual Fund",
        "category": "equity",
        "sub_category": "index",
    },
    {
        "url": "https://groww.in/mutual-funds/jioblackrock-large-cap-fund-direct-growth",
        "source_type": "groww_scheme_page",
        "scheme_name": "JioBlackRock Large Cap Fund",
        "scheme_id": "jbr_large_cap",
        "amc": "JioBlackRock Mutual Fund",
        "category": "equity",
        "sub_category": "large_cap",
    },
    {
        "url": "https://groww.in/mutual-funds/jioblackrock-money-market-fund-direct-growth",
        "source_type": "groww_scheme_page",
        "scheme_name": "JioBlackRock Money Market Fund",
        "scheme_id": "jbr_money_market",
        "amc": "JioBlackRock Mutual Fund",
        "category": "debt",
        "sub_category": "money_market",
    },
    {
        "url": "https://groww.in/mutual-funds/jioblackrock-overnight-fund-direct-growth",
        "source_type": "groww_scheme_page",
        "scheme_name": "JioBlackRock Overnight Fund",
        "scheme_id": "jbr_overnight",
        "amc": "JioBlackRock Mutual Fund",
        "category": "debt",
        "sub_category": "overnight",
    },
    {
        "url": "https://groww.in/mutual-funds/jioblackrock-arbitrage-fund-direct-growth",
        "source_type": "groww_scheme_page",
        "scheme_name": "JioBlackRock Arbitrage Fund",
        "scheme_id": "jbr_arbitrage",
        "amc": "JioBlackRock Mutual Fund",
        "category": "hybrid",
        "sub_category": "arbitrage",
    },
    {
        "url": "https://groww.in/mutual-funds/jioblackrock-nifty-8-13-yr-g-sec-index-fund-direct-growth",
        "source_type": "groww_scheme_page",
        "scheme_name": "JioBlackRock Nifty 8-13 Yr G-Sec Index Fund",
        "scheme_id": "jbr_nifty_gsec_8_13",
        "amc": "JioBlackRock Mutual Fund",
        "category": "debt",
        "sub_category": "index",
    },
    {
        "url": "https://groww.in/mutual-funds/jioblackrock-short-duration-fund-direct-growth",
        "source_type": "groww_scheme_page",
        "scheme_name": "JioBlackRock Short Duration Fund",
        "scheme_id": "jbr_short_duration",
        "amc": "JioBlackRock Mutual Fund",
        "category": "debt",
        "sub_category": "short_duration",
    },
    {
        "url": "https://groww.in/mutual-funds/jioblackrock-low-duration-fund-direct-growth",
        "source_type": "groww_scheme_page",
        "scheme_name": "JioBlackRock Low Duration Fund",
        "scheme_id": "jbr_low_duration",
        "amc": "JioBlackRock Mutual Fund",
        "category": "debt",
        "sub_category": "low_duration",
    },
]
